title: Scary Spot the Difference
hero_image: images/banner.png
description: Make a scary spot the difference game Scratch
original_url: https://raspberrypi.org/learning/scary-spot-the-difference
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Scary Spot the Difference - Scratch
- title: Gathering the assets
- title: Setting up your Scratch project
- title: Setting the scene
- title: Making the scary picture appear
- title: Adding sound
- title: What next?