---
title: Scary 'spot the difference'
hero_image: images/banner.png
description: Make a scary 'spot the difference' game in Scratch
original_url: https://raspberrypi.org/learning/scary-spot-the-difference
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0
last_tested: 2019-04-11
steps:
- title: Introduction
- title: Get started
- title: Detect mouse clicks
  completion:
  - engaged
- title: Add a random pause
- title: Add a scream
  completion:
  - internal
- title: What next?
  completion:
  - external
