title: Scary Spot the Difference
hero_image: images/banner.png
description: Make a scary spot the difference game Scratch
original_url: https://raspberrypi.org/learning/scary-spot-the-difference
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0
last_tested: 2019-04-11
steps: 
- title: Introduction
- title: Getting started
- title: Detecting mouse clicks
- title: Random pauses
- title: Add a scream
- title: What next?
